#!/usr/bin/env bash
#
# Based on BurntSushis version available at https://github.com/BurntSushi/advent-of-code/blob/master/setup-day

if [ "$#" != 2 ]; then
    echo "Usage: $(basename "$0") <year> <day-number>" >&2
    exit 1
fi

if [ ! -d .git ]; then
    echo "Error: must be run from root of advent-of-code repository" >&2
    exit 1
fi

YEAR="${1}"
DAY="$(printf "%02d" "${2}")"

cargo new --bin "${YEAR}/${DAY}" --name "aoc_${YEAR}_${DAY}"
mkdir -p "${YEAR}/${DAY}/input"
