[package]
name = "aoc_2020_08"
version = "0.1.0"
authors = ["Bruno Kirschner <bruno.kirschner@online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "^0.4.0"